# Generated by Django 5.1.2 on 2024-11-04 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Guruh nomi')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': '2. Guruh',
                'verbose_name_plural': '2. Guruhlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Yangilik haqidi')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name="Rasm qo'shish")),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': '4 Yangilik',
                'verbose_name_plural': '4 Yangiliklar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Foydalanuvchi nomi')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email manzili')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
                ('ins_groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_ins', to='attandance.insgroups', verbose_name="Biriktish kerak bo'lgan Guruh")),
            ],
            options={
                'verbose_name': '3 Student',
                'verbose_name_plural': '3 Studentlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coming', models.BooleanField(blank=True, default=False, null=True, verbose_name='Davamoat')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_ins', to=settings.AUTH_USER_MODEL, verbose_name="Bo'sh kelsa bugun u qatnashmagan, Agar qanashgan bo'lsa ichi to'la bo'ladi")),
            ],
            options={
                'verbose_name': '5 Davomat',
                'verbose_name_plural': '5 Davomat',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AttandanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='attandance/', verbose_name='Yuklangan fayl')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attandance_group', to='attandance.insgroups', verbose_name="Biriktish kerak bo'lgan Guruh")),
            ],
            options={
                'verbose_name': "5 Davomat uchun yuklangan ma'lumotlar",
                'verbose_name_plural': "5 Davomat uchun yuklangan ma'lumotlar",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tashkilot nomi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Tashkilot manzili')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tashkilot telefon raqami')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Tashkilot ma'suli")),
            ],
            options={
                'verbose_name': '1. Tashkilot',
                'verbose_name_plural': '1. Tashkilotlar',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='insgroups',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_group', to='attandance.organization', verbose_name="Biriktish kerak bo'lgan Tashkilot"),
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_commands_file', models.FileField(blank=True, null=True, upload_to='org_file/', verbose_name="Tashkilot buyrug'i")),
                ('irrigation_commands_file', models.FileField(blank=True, null=True, upload_to='irrigation_file/', verbose_name="Tiiamebb buyrug'i")),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_doc', to='attandance.organization', verbose_name="Biriktish kerak bo'lgan Tashkilot")),
            ],
        ),
    ]
