# Generated by Django 5.1.2 on 2024-11-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id'], 'verbose_name': '3 Foydalanuvchilar', 'verbose_name_plural': '3 Foydalanuvchilar'},
        ),
    ]
